# Acá inicializo cosas de la gema aws

AMAZON_ACCESS_KEY_ID = ENV["AMAZON_ACCESS_KEY_ID"]
AMAZON_SECRET_ACCESS_KEY = ENV["AMAZON_SECRET_ACCESS_KEY"]
AMAZON_SECRET_ACCESS_KEY_EC2 = ENV["AMAZON_SECRET_ACCESS_KEY_EC2"]
AMAZON_ACCESS_KEY_ID_EC2 = ENV["AMAZON_ACCESS_KEY_ID_EC2"]

